import type { NextApiRequest, NextApiResponse } from 'next';

export default (req: NextApiRequest, res: NextApiResponse): void => {
  res.status(200).json([
    {
      title: 'Praktik Imunisasi pada Masa Pandemi Covid-19',
      short_description: `<p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
        <p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>`,
      category_name: 'RISET',
      category_id: 1,
      description: 'desc',
      id: '1',
      image:
        'https://www.ciputrahospital.com/wp-content/uploads/2021/01/shutterstock_546477442resizeee.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '2',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '3',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '4',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '5',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '6',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '7',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '8',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '9',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '10',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '11',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '12',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '13',
      image: '/images/hk-haibin.jpg',
    },
    {
      title: 'HK Haibin China dan USU Pertukaran Mahasiswa',
      short_description: `R III mengatakan, kerja sama antara kedua belah pihak ini bertujuan untuk pertukaran mahasiswa antara HK Haibin dan USU di bidang magister.`,
      category_name: 'KAMPUS_SEHAT',
      category_id: 2,
      description: 'desc',
      id: '14',
      image: '/images/hk-haibin.jpg',
    },
  ]);
};
